using System.Collections.Generic;

namespace TeeSharp.MasterServer
{
    public class CountryInfo
    {
        public readonly string ShortName;
        public readonly string FullName;

        private CountryInfo(string sh, string full)
        {
            ShortName = sh;
            FullName = full;
        }

        public static CountryInfo GetCountryInfo(int code)
        {
            if (_countriesInfo.ContainsKey(code))
                return _countriesInfo[code];
            return _countriesInfo[-1];
        }

        private static readonly Dictionary<int, CountryInfo> _countriesInfo = new Dictionary<int, CountryInfo>
        {
            { -1    , new CountryInfo("default", "none") },
            { 901   , new CountryInfo("XEN", "England") },
            { 902   , new CountryInfo("XNI", "Northern Ireland") },
            { 903   , new CountryInfo("XSC", "Scotland") },
            { 904   , new CountryInfo("XWA", "Wales") },
            /* ISO 3166-1 */
            { 4     , new CountryInfo("AF", "Afghanistan") },
            { 248   , new CountryInfo("AX", "Уland Islands") },
            { 8     , new CountryInfo("AL", "Albania") },
            { 12    , new CountryInfo("DZ", "Algeria") },
            { 16    , new CountryInfo("AS", "American Samoa") },
            { 20    , new CountryInfo("AD", "Andorra") },
            { 24    , new CountryInfo("AO", "Angola") },
            { 660   , new CountryInfo("AI", "Anguilla") },
            { 10    , new CountryInfo("AQ", "Antarctica") },
            { 028   , new CountryInfo("AG", "Antigua and Barbuda") },
            { 032   , new CountryInfo("AR", "Argentina") },
            { 051   , new CountryInfo("AM", "Armenia") },
            { 533   , new CountryInfo("AW", "Aruba") },
            { 36    , new CountryInfo("AU", "Australia") },
            { 40    , new CountryInfo("AT", "Austria") },
            { 31    , new CountryInfo("AZ", "Azerbaijan") },
            { 44    , new CountryInfo("BS", "Bahamas") },
            { 48    , new CountryInfo("BH", "Bahrain") },
            { 50    , new CountryInfo("BD", "Bangladesh") },
            { 52    , new CountryInfo("BB", "Barbados") },
            { 112   , new CountryInfo("BY", "Belarus") },
            { 56    , new CountryInfo("BE", "Belgium") },
            { 84    , new CountryInfo("BZ", "Belize") },
            { 204   , new CountryInfo("BJ", "Benin") },
            { 60    , new CountryInfo("BM", "Bermuda") },
            { 64    , new CountryInfo("BT", "Bhutan") },
            { 68    , new CountryInfo("BO", "Bolivia, Plurinational State of") },
            { 535   , new CountryInfo("BQ", "Bonaire, Sint Eustatius and Saba") },
            { 70    , new CountryInfo("BA", "Bosnia and Herzegovina") },
            { 72    , new CountryInfo("BW", "Botswana") },
            { 74    , new CountryInfo("BV", "Bouvet Island") },
            { 76    , new CountryInfo("BR", "Brazil") },
            { 86    , new CountryInfo("IO", "British Indian Ocean Territory") },
            { 96    , new CountryInfo("BN", "Brunei Darussalam") },
            { 100   , new CountryInfo("BG", "Bulgaria") },
            { 854   , new CountryInfo("BF", "Burkina Faso") },
            { 108   , new CountryInfo("BI", "Burundi") },
            { 116   , new CountryInfo("KH", "Cambodia") },
            { 120   , new CountryInfo("CM", "Cameroon") },
            { 124   , new CountryInfo("CA", "Canada") },
            { 132   , new CountryInfo("CV", "Cape Verde") },
            { 136   , new CountryInfo("KY", "Cayman Islands") },
            { 140   , new CountryInfo("CF", "Central African Republic") },
            { 148   , new CountryInfo("TD", "Chad") },
            { 152   , new CountryInfo("CL", "Chile") },
            { 156   , new CountryInfo("CN", "China") },
            { 162   , new CountryInfo("CX", "Christmas Island") },
            { 166   , new CountryInfo("CC", "Cocos (Keeling) Islands") },
            { 170   , new CountryInfo("CO", "Colombia") },
            { 174   , new CountryInfo("KM", "Comoros") },
            { 178   , new CountryInfo("CG", "Congo") },
            { 180   , new CountryInfo("CD", "Congo, the Democratic Republic of the") },
            { 184   , new CountryInfo("CK", "Cook Islands") },
            { 188   , new CountryInfo("CR", "Costa Rica") },
            { 384   , new CountryInfo("CI", "CУДte d\'Ivoire") },
            { 191   , new CountryInfo("HR", "Croatia") },
            { 192   , new CountryInfo("CU", "Cuba") },
            { 531   , new CountryInfo("CW", "CuraУЇao") },
            { 196   , new CountryInfo("CY", "Cyprus") },
            { 203   , new CountryInfo("CZ", "Czech Republic") },
            { 208   , new CountryInfo("DK", "Denmark") },
            { 262   , new CountryInfo("DJ", "Djibouti") },
            { 212   , new CountryInfo("DM", "Dominica") },
            { 214   , new CountryInfo("DO", "Dominican Republic") },
            { 218   , new CountryInfo("EC", "Ecuador") },
            { 818   , new CountryInfo("EG", "Egypt") },
            { 222   , new CountryInfo("SV", "El Salvador") },
            { 226   , new CountryInfo("GQ", "Equatorial Guinea") },
            { 232   , new CountryInfo("ER", "Eritrea") },
            { 233   , new CountryInfo("EE", "Estonia") },
            { 231   , new CountryInfo("ET", "Ethiopia") },
            { 238   , new CountryInfo("FK", "Falkland Islands (Malvinas)") },
            { 234   , new CountryInfo("FO", "Faroe Islands") },
            { 242   , new CountryInfo("FJ", "Fiji") },
            { 246   , new CountryInfo("FI", "Finland") },
            { 250   , new CountryInfo("FR", "France") },
            { 254   , new CountryInfo("GF", "French Guiana") },
            { 258   , new CountryInfo("PF", "French Polynesia") },
            { 260   , new CountryInfo("TF", "French Southern Territories") },
            { 266   , new CountryInfo("GA", "Gabon") },
            { 270   , new CountryInfo("GM", "Gambia") },
            { 268   , new CountryInfo("GE", "Georgia") },
            { 276   , new CountryInfo("DE", "Germany") },
            { 288   , new CountryInfo("GH", "Ghana") },
            { 292   , new CountryInfo("GI", "Gibraltar") },
            { 300   , new CountryInfo("GR", "Greece") },
            { 304   , new CountryInfo("GL", "Greenland") },
            { 308   , new CountryInfo("GD", "Grenada") },
            { 312   , new CountryInfo("GP", "Guadeloupe") },
            { 316   , new CountryInfo("GU", "Guam") },
            { 320   , new CountryInfo("GT", "Guatemala") },
            { 831   , new CountryInfo("GG", "Guernsey") },
            { 324   , new CountryInfo("GN", "Guinea") },
            { 624   , new CountryInfo("GW", "Guinea-Bissau") },
            { 328   , new CountryInfo("GY", "Guyana") },
            { 332   , new CountryInfo("HT", "Haiti") },
            { 334   , new CountryInfo("HM", "Heard Island and McDonald Islands") },
            { 336   , new CountryInfo("VA", "Holy See (Vatican City State)") },
            { 340   , new CountryInfo("HN", "Honduras") },
            { 344   , new CountryInfo("HK", "Hong Kong") },
            { 348   , new CountryInfo("HU", "Hungary") },
            { 352   , new CountryInfo("IS", "Iceland") },
            { 356   , new CountryInfo("IN", "India") },
            { 360   , new CountryInfo("ID", "Indonesia") },
            { 364   , new CountryInfo("IR", "Iran, Islamic Republic of") },
            { 368   , new CountryInfo("IQ", "Iraq") },
            { 372   , new CountryInfo("IE", "Ireland") },
            { 833   , new CountryInfo("IM", "Isle of Man") },
            { 376   , new CountryInfo("IL", "Israel") },
            { 380   , new CountryInfo("IT", "Italy") },
            { 388   , new CountryInfo("JM", "Jamaica") },
            { 392   , new CountryInfo("JP", "Japan") },
            { 832   , new CountryInfo("JE", "Jersey") },
            { 400   , new CountryInfo("JO", "Jordan") },
            { 398   , new CountryInfo("KZ", "Kazakhstan") },
            { 404   , new CountryInfo("KE", "Kenya") },
            { 296   , new CountryInfo("KI", "Kiribati") },
            { 408   , new CountryInfo("KP", "Korea, Democratic People\'s Republic of") },
            { 410   , new CountryInfo("KR", "Korea, Republic of") },
            { 414   , new CountryInfo("KW", "Kuwait") },
            { 417   , new CountryInfo("KG", "Kyrgyzstan") },
            { 418   , new CountryInfo("LA", "Lao People\'s Democratic Republic") },
            { 428   , new CountryInfo("LV", "Latvia") },
            { 422   , new CountryInfo("LB", "Lebanon") },
            { 426   , new CountryInfo("LS", "Lesotho") },
            { 430   , new CountryInfo("LR", "Liberia") },
            { 434   , new CountryInfo("LY", "Libya") },
            { 438   , new CountryInfo("LI", "Liechtenstein") },
            { 440   , new CountryInfo("LT", "Lithuania") },
            { 442   , new CountryInfo("LU", "Luxembourg") },
            { 446   , new CountryInfo("MO", "Macao") },
            { 807   , new CountryInfo("MK", "Macedonia, the former Yugoslav Republic of") },
            { 450   , new CountryInfo("MG", "Madagascar") },
            { 454   , new CountryInfo("MW", "Malawi") },
            { 458   , new CountryInfo("MY", "Malaysia") },
            { 462   , new CountryInfo("MV", "Maldives") },
            { 466   , new CountryInfo("ML", "Mali") },
            { 470   , new CountryInfo("MT", "Malta") },
            { 584   , new CountryInfo("MH", "Marshall Islands") },
            { 474   , new CountryInfo("MQ", "Martinique") },
            { 478   , new CountryInfo("MR", "Mauritania") },
            { 480   , new CountryInfo("MU", "Mauritius") },
            { 175   , new CountryInfo("YT", "Mayotte") },
            { 484   , new CountryInfo("MX", "Mexico") },
            { 583   , new CountryInfo("FM", "Micronesia, Federated States of") },
            { 498   , new CountryInfo("MD", "Moldova, Republic of") },
            { 492   , new CountryInfo("MC", "Monaco") },
            { 496   , new CountryInfo("MN", "Mongolia") },
            { 499   , new CountryInfo("ME", "Montenegro") },
            { 500   , new CountryInfo("MS", "Montserrat") },
            { 504   , new CountryInfo("MA", "Morocco") },
            { 508   , new CountryInfo("MZ", "Mozambique") },
            { 104   , new CountryInfo("MM", "Myanmar") },
            { 516   , new CountryInfo("NA", "Namibia") },
            { 520   , new CountryInfo("NR", "Nauru") },
            { 524   , new CountryInfo("NP", "Nepal") },
            { 528   , new CountryInfo("NL", "Netherlands") },
            { 540   , new CountryInfo("NC", "New Caledonia") },
            { 554   , new CountryInfo("NZ", "New Zealand") },
            { 558   , new CountryInfo("NI", "Nicaragua") },
            { 562   , new CountryInfo("NE", "Niger") },
            { 566   , new CountryInfo("NG", "Nigeria") },
            { 570   , new CountryInfo("NU", "Niue") },
            { 574   , new CountryInfo("NF", "Norfolk Island") },
            { 580   , new CountryInfo("MP", "Northern Mariana Islands") },
            { 578   , new CountryInfo("NO", "Norway") },
            { 512   , new CountryInfo("OM", "Oman") },
            { 586   , new CountryInfo("PK", "Pakistan") },
            { 585   , new CountryInfo("PW", "Palau") },
            { 275   , new CountryInfo("PS", "Palestinian Territory, Occupied") },
            { 591   , new CountryInfo("PA", "Panama") },
            { 598   , new CountryInfo("PG", "Papua New Guinea") },
            { 600   , new CountryInfo("PY", "Paraguay") },
            { 604   , new CountryInfo("PE", "Peru") },
            { 608   , new CountryInfo("PH", "Philippines") },
            { 612   , new CountryInfo("PN", "Pitcairn") },
            { 616   , new CountryInfo("PL", "Poland") },
            { 620   , new CountryInfo("PT", "Portugal") },
            { 630   , new CountryInfo("PR", "Puerto Rico") },
            { 634   , new CountryInfo("QA", "Qatar") },
            { 638   , new CountryInfo("RE", "RУЉunion") },
            { 642   , new CountryInfo("RO", "Romania") },
            { 643   , new CountryInfo("RU", "Russian Federation") },
            { 646   , new CountryInfo("RW", "Rwanda") },
            { 652   , new CountryInfo("BL", "Saint BarthУЉlemy") },
            { 654   , new CountryInfo("SH", "Saint Helena, Ascension and Tristan da Cunha") },
            { 659   , new CountryInfo("KN", "Saint Kitts and Nevis") },
            { 662   , new CountryInfo("LC", "Saint Lucia") },
            { 663   , new CountryInfo("MF", "Saint Martin (French part)") },
            { 666   , new CountryInfo("PM", "Saint Pierre and Miquelon") },
            { 670   , new CountryInfo("VC", "Saint Vincent and the Grenadines") },
            { 882   , new CountryInfo("WS", "Samoa") },
            { 674   , new CountryInfo("SM", "San Marino") },
            { 678   , new CountryInfo("ST", "Sao Tome and Principe") },
            { 682   , new CountryInfo("SA", "Saudi Arabia") },
            { 686   , new CountryInfo("SN", "Senegal") },
            { 688   , new CountryInfo("RS", "Serbia") },
            { 690   , new CountryInfo("SC", "Seychelles") },
            { 694   , new CountryInfo("SL", "Sierra Leone") },
            { 702   , new CountryInfo("SG", "Singapore") },
            { 534   , new CountryInfo("SX", "Sint Maarten (Dutch part)") },
            { 703   , new CountryInfo("SK", "Slovakia") },
            { 705   , new CountryInfo("SI", "Slovenia") },
            { 90    , new CountryInfo("SB", "Solomon Islands") },
            { 706   , new CountryInfo("SO", "Somalia") },
            { 710   , new CountryInfo("ZA", "South Africa") },
            { 239   , new CountryInfo("GS", "South Georgia and the South Sandwich Islands") },
            { 728   , new CountryInfo("SS", "South Sudan") },
            { 724   , new CountryInfo("ES", "Spain") },
            { 144   , new CountryInfo("LK", "Sri Lanka") },
            { 729   , new CountryInfo("SD", "Sudan") },
            { 740   , new CountryInfo("SR", "Suriname") },
            { 744   , new CountryInfo("SJ", "Svalbard and Jan Mayen") },
            { 748   , new CountryInfo("SZ", "Swaziland") },
            { 752   , new CountryInfo("SE", "Sweden") },
            { 756   , new CountryInfo("CH", "Switzerland") },
            { 760   , new CountryInfo("SY", "Syrian Arab Republic") },
            { 158   , new CountryInfo("TW", "Taiwan, Province of China") },
            { 762   , new CountryInfo("TJ", "Tajikistan") },
            { 834   , new CountryInfo("TZ", "Tanzania, United Republic of") },
            { 764   , new CountryInfo("TH", "Thailand") },
            { 626   , new CountryInfo("TL", "Timor-Leste") },
            { 768   , new CountryInfo("TG", "Togo") },
            { 772   , new CountryInfo("TK", "Tokelau") },
            { 776   , new CountryInfo("TO", "Tonga") },
            { 780   , new CountryInfo("TT", "Trinidad and Tobago") },
            { 788   , new CountryInfo("TN", "Tunisia") },
            { 792   , new CountryInfo("TR", "Turkey") },
            { 795   , new CountryInfo("TM", "Turkmenistan") },
            { 796   , new CountryInfo("TC", "Turks and Caicos Islands") },
            { 798   , new CountryInfo("TV", "Tuvalu") },
            { 800   , new CountryInfo("UG", "Uganda") },
            { 804   , new CountryInfo("UA", "Ukraine") },
            { 784   , new CountryInfo("AE", "United Arab Emirates") },
            { 826   , new CountryInfo("GB", "United Kingdom") },
            { 840   , new CountryInfo("US", "United States") },
            { 581   , new CountryInfo("UM", "United States Minor Outlying Islands") },
            { 858   , new CountryInfo("UY", "Uruguay") },
            { 860   , new CountryInfo("UZ", "Uzbekistan") },
            { 548   , new CountryInfo("VU", "Vanuatu") },
            { 862   , new CountryInfo("VE", "Venezuela, Bolivarian Republic of") },
            { 704   , new CountryInfo("VN", "Viet Nam") },
            { 92    , new CountryInfo("VG", "Virgin Islands, British") },
            { 850   , new CountryInfo("VI", "Virgin Islands, U.S.") },
            { 876   , new CountryInfo("WF", "Wallis and Futuna") },
            { 732   , new CountryInfo("EH", "Western Sahara") },
            { 887   , new CountryInfo("YE", "Yemen") },
            { 894   , new CountryInfo("ZM", "Zambia") },
            { 716   , new CountryInfo("ZW", "Zimbabwe") },
        };
    }
}