<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>default</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.13.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TeeSharp.Core\TeeSharp.Core.csproj" />
      <ProjectReference Include="..\TeeSharp.Map\TeeSharp.Map.csproj" />
      <ProjectReference Include="..\TeeSharp.MasterServer\TeeSharp.MasterServer.csproj" />
      <ProjectReference Include="..\TeeSharp.Network\TeeSharp.Network.csproj" />
    </ItemGroup>

</Project>
